name: images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  pull_request_target:
    types: [labeled]
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

env:
  REGISTRY_IMAGE: ghcr.io/markentier/utilities

jobs:
  utilities:
    # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      - run: docker version
      - run: docker info
      - run: docker system df -v
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry (ghcr.io)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}
      -
        name: Build and push
        run: make all.ghcr BUILDX_FLAGS="--cache-from=type=gha --cache-to=type=gha"
